add_newline = true

[character]
symbol = "➜"

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 5

[docker_context]
disabled = false

[git_state]
disabled = false
